inherit_from:
  - https://raw.githubusercontent.com/news-scraper/styles/master/docs/rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'

Rails:
  Enabled: true

