default: &default
  host: localhost
  adapter: postgresql
  encoding: utf-8

development:
  <<: *default
  database: news_scraper_records_development

test:
  <<: *default
  database: news_scraper_records_test

production:
  <<: *default
  database: news_scraper_records
